/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

/**
 *
 * @author WINDOWS 10
 */
public class KalkutalorScientific extends javax.swing.JFrame {
String angka="";
double jumlah, angka1, angka2;
int pilih;

    /**
     * Creates new form KalkutalorScientific
     */
    public KalkutalorScientific() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        buttonPangkat = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonKali = new javax.swing.JButton();
        buttonPhi = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        buttonKurang = new javax.swing.JButton();
        buttonBagi = new javax.swing.JButton();
        buttonSin = new javax.swing.JButton();
        buttonCos = new javax.swing.JButton();
        buttonTan = new javax.swing.JButton();
        buttonLog = new javax.swing.JButton();
        buttonAkarx = new javax.swing.JButton();
        buttonPersen = new javax.swing.JButton();
        buttonAkar = new javax.swing.JButton();
        buttonAngka2 = new javax.swing.JButton();
        buttonAngka3 = new javax.swing.JButton();
        buttonAngka4 = new javax.swing.JButton();
        buttonAngka5 = new javax.swing.JButton();
        buttonAngka6 = new javax.swing.JButton();
        buttonAngka7 = new javax.swing.JButton();
        buttonAngka8 = new javax.swing.JButton();
        buttonAngka9 = new javax.swing.JButton();
        buttonAngka0 = new javax.swing.JButton();
        buttonAngka1 = new javax.swing.JButton();
        buttonHasil = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonModulus = new javax.swing.JButton();
        buttonBS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Scientific");
        setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(null);

        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        jPanel1.add(display);
        display.setBounds(30, 70, 340, 90);

        buttonPangkat.setText("x^2");
        buttonPangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPangkatActionPerformed(evt);
            }
        });
        jPanel1.add(buttonPangkat);
        buttonPangkat.setBounds(310, 330, 60, 40);

        buttonHapus.setText("C");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });
        jPanel1.add(buttonHapus);
        buttonHapus.setBounds(30, 180, 60, 40);

        buttonKali.setText("*");
        buttonKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKaliActionPerformed(evt);
            }
        });
        jPanel1.add(buttonKali);
        buttonKali.setBounds(240, 330, 60, 40);

        buttonPhi.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        buttonPhi.setText("π");
        buttonPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPhiActionPerformed(evt);
            }
        });
        jPanel1.add(buttonPhi);
        buttonPhi.setBounds(310, 430, 60, 40);

        buttonTambah.setText("+");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });
        jPanel1.add(buttonTambah);
        buttonTambah.setBounds(240, 380, 60, 40);

        buttonKurang.setText("-");
        buttonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKurangActionPerformed(evt);
            }
        });
        jPanel1.add(buttonKurang);
        buttonKurang.setBounds(240, 430, 60, 40);

        buttonBagi.setText("/");
        buttonBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBagiActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBagi);
        buttonBagi.setBounds(240, 280, 60, 40);

        buttonSin.setText("sin");
        buttonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSinActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSin);
        buttonSin.setBounds(100, 180, 60, 40);

        buttonCos.setText("cos");
        buttonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCosActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCos);
        buttonCos.setBounds(170, 180, 60, 40);

        buttonTan.setText("tan");
        buttonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTanActionPerformed(evt);
            }
        });
        jPanel1.add(buttonTan);
        buttonTan.setBounds(240, 180, 60, 40);

        buttonLog.setText("log");
        buttonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLog);
        buttonLog.setBounds(310, 230, 60, 40);

        buttonAkarx.setText("x^y");
        buttonAkarx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAkarxActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAkarx);
        buttonAkarx.setBounds(310, 280, 60, 40);

        buttonPersen.setText("%");
        buttonPersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersenActionPerformed(evt);
            }
        });
        jPanel1.add(buttonPersen);
        buttonPersen.setBounds(170, 380, 60, 40);

        buttonAkar.setText("√");
        buttonAkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAkarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAkar);
        buttonAkar.setBounds(310, 380, 60, 40);

        buttonAngka2.setText("2");
        buttonAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAngka2ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAngka2);
        buttonAngka2.setBounds(100, 230, 60, 40);

        buttonAngka3.setText("3");
        buttonAngka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAngka3ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAngka3);
        buttonAngka3.setBounds(170, 230, 60, 40);

        buttonAngka4.setText("4");
        buttonAngka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAngka4ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAngka4);
        buttonAngka4.setBounds(30, 280, 60, 40);

        buttonAngka5.setText("5");
        buttonAngka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAngka5ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAngka5);
        buttonAngka5.setBounds(100, 280, 60, 40);

        buttonAngka6.setText("6");
        buttonAngka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAngka6ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAngka6);
        buttonAngka6.setBounds(170, 280, 60, 40);

        buttonAngka7.setText("7");
        buttonAngka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAngka7ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAngka7);
        buttonAngka7.setBounds(30, 330, 60, 40);

        buttonAngka8.setText("8");
        buttonAngka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAngka8ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAngka8);
        buttonAngka8.setBounds(100, 330, 60, 40);

        buttonAngka9.setText("9");
        buttonAngka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAngka9ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAngka9);
        buttonAngka9.setBounds(170, 330, 60, 40);

        buttonAngka0.setText("0");
        buttonAngka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAngka0ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAngka0);
        buttonAngka0.setBounds(30, 380, 130, 40);

        buttonAngka1.setText("1");
        buttonAngka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAngka1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAngka1);
        buttonAngka1.setBounds(30, 230, 60, 40);

        buttonHasil.setText("=");
        buttonHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHasilActionPerformed(evt);
            }
        });
        jPanel1.add(buttonHasil);
        buttonHasil.setBounds(30, 430, 130, 40);

        jButton1.setText(".");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 430, 60, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Kalkulator Scientific");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 30, 230, 20);

        buttonModulus.setText("mdls");
        buttonModulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModulusActionPerformed(evt);
            }
        });
        jPanel1.add(buttonModulus);
        buttonModulus.setBounds(240, 230, 60, 40);

        buttonBS.setText("<--");
        buttonBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBSActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBS);
        buttonBS.setBounds(310, 183, 60, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        display.setText("");
        angka1=0.0;
        angka2=0.0;
        jumlah=0.0;
        angka="";
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSinActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText(" Sin ");
        angka="";
        pilih=10;
    }//GEN-LAST:event_buttonSinActionPerformed

    private void buttonAngka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAngka1ActionPerformed
        // TODO add your handling code here:
        angka += "1";
        display.setText(angka);
    }//GEN-LAST:event_buttonAngka1ActionPerformed

    private void buttonAngka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAngka2ActionPerformed
        // TODO add your handling code here:
        angka += "2";
        display.setText(angka);
    }//GEN-LAST:event_buttonAngka2ActionPerformed

    private void buttonAngka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAngka3ActionPerformed
        // TODO add your handling code here:
        angka += "3";
        display.setText(angka);
    }//GEN-LAST:event_buttonAngka3ActionPerformed

    private void buttonAngka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAngka4ActionPerformed
        // TODO add your handling code here:
        angka += "4";
        display.setText(angka);
    }//GEN-LAST:event_buttonAngka4ActionPerformed

    private void buttonAngka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAngka5ActionPerformed
        // TODO add your handling code here:
        angka += "5";
        display.setText(angka);
    }//GEN-LAST:event_buttonAngka5ActionPerformed

    private void buttonAngka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAngka6ActionPerformed
        // TODO add your handling code here:
        angka += "6";
        display.setText(angka);
    }//GEN-LAST:event_buttonAngka6ActionPerformed

    private void buttonAngka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAngka7ActionPerformed
        // TODO add your handling code here:
        angka += "7";
        display.setText(angka);
    }//GEN-LAST:event_buttonAngka7ActionPerformed

    private void buttonAngka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAngka8ActionPerformed
        // TODO add your handling code here:
        angka += "8";
        display.setText(angka);
    }//GEN-LAST:event_buttonAngka8ActionPerformed

    private void buttonAngka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAngka9ActionPerformed
        // TODO add your handling code here:
        angka += "9";
        display.setText(angka);
    }//GEN-LAST:event_buttonAngka9ActionPerformed

    private void buttonAngka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAngka0ActionPerformed
        // TODO add your handling code here:
        angka += "0";
        display.setText(angka);
    }//GEN-LAST:event_buttonAngka0ActionPerformed

    private void buttonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKurangActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("-");   
        angka="";   
        pilih=2;
    }//GEN-LAST:event_buttonKurangActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("+");
        angka="";
        pilih=1;
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKaliActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("*");
        angka="";
        pilih=3;
    }//GEN-LAST:event_buttonKaliActionPerformed

    private void buttonBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBagiActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("/");
        angka="";
        pilih=4;
    }//GEN-LAST:event_buttonBagiActionPerformed

    private void buttonHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHasilActionPerformed
        // TODO add your handling code here:
          switch(pilih){
          case 1:
          angka2 = Double.parseDouble(angka);
          jumlah = angka1 + angka2;
          angka = Double.toString(jumlah);
          display.setText(angka);
          break;
          case 2:
          angka2 = Double.parseDouble(angka);
          jumlah = angka1 - angka2;
          angka = Double.toString(jumlah);
          display.setText(angka);
          break;
          case 3:
          angka2 = Double.parseDouble(angka);
          jumlah = angka1 * angka2;
          angka = Double.toString(jumlah);
          display.setText(angka);
          break;
          case 4:
          angka2 = Double.parseDouble(angka);
          jumlah = angka1 / angka2;
          angka = Double.toString(jumlah);
          display.setText(angka);
          break;
          case 5:
               
          jumlah = Math.pow(angka1, 2);
          angka = Double.toString(jumlah);
          display.setText(angka);
          break;
                
          case 6:
              
          jumlah = Math.sqrt(angka1);
          angka = Double.toString(jumlah);
          display.setText(angka);
          break;
          
          case 7:
          angka2 = Double.parseDouble(angka);
          jumlah = Math.pow(angka1, angka2);
          angka = Double.toString(jumlah);
          display.setText(angka);  
          break;
          case 8:
             
          jumlah = angka1* 3.14;
          angka = Double.toString(jumlah);
          display.setText(angka);  
          break;
     
               
          case 9:
            
          jumlah = angka1/100;
          angka = Double.toString(jumlah);
          display.setText(angka); 
          break;
          case 10:
            
          jumlah = Math.sin(angka1);
          angka = Double.toString(jumlah);
          display.setText(angka); 
          break;
          case 11:   
         jumlah = Math.cos(angka1);
         angka = Double.toString(jumlah);
         display.setText(angka); 
         break;
         case 12:
         jumlah = Math.tan(angka1);
         angka = Double.toString(jumlah);
         display.setText(angka); 
         break;
         case 13:
         angka2 = Double.parseDouble(angka);
         jumlah = Math.log(angka1);
         angka = Double.toString(jumlah);
         display.setText(angka);
         break;
         case 14:
          angka2 = Double.parseDouble(angka);
          jumlah = angka1 % angka2;
          angka = Double.toString(jumlah);
          display.setText(angka); 

         default:
         break;
         }
    }//GEN-LAST:event_buttonHasilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        angka += ".";
        display.setText(angka);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCosActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText(" Cos ");
        angka="";
        pilih=11;
    }//GEN-LAST:event_buttonCosActionPerformed

    private void buttonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTanActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText(" Tan ");
        angka="";
        pilih=12;
    }//GEN-LAST:event_buttonTanActionPerformed

    private void buttonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText(" Log ");
        angka="";
        pilih=13; 
    }//GEN-LAST:event_buttonLogActionPerformed

    private void buttonPangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPangkatActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("^");
        angka="";
        pilih=5;
    }//GEN-LAST:event_buttonPangkatActionPerformed

    private void buttonAkarxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAkarxActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("^");
        angka="";
        pilih=7;    
    }//GEN-LAST:event_buttonAkarxActionPerformed

    private void buttonAkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAkarActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("√");
        angka="";
        pilih=6;
    }//GEN-LAST:event_buttonAkarActionPerformed

    private void buttonPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPhiActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText(" π ");
        angka="";
        pilih=8;
    }//GEN-LAST:event_buttonPhiActionPerformed

    private void buttonPersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersenActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("% ");
        angka="";
        pilih=9; 
    }//GEN-LAST:event_buttonPersenActionPerformed

    private void buttonBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBSActionPerformed
        // TODO add your handling code here:
       display.getText().length();
       StringBuilder all = new StringBuilder (display.getText());
       char end = all.charAt(all.length()-1);
       all.deleteCharAt(all.length()-1);
       display.setText(all.toString());
       angka = display.getText();
       if (display.getText().length() > 0){
       buttonBS.setEnabled(true);
        }
        
    }//GEN-LAST:event_buttonBSActionPerformed

    private void buttonModulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModulusActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("%");
        angka="";
        pilih=14;
    }//GEN-LAST:event_buttonModulusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkutalorScientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkutalorScientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkutalorScientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkutalorScientific.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkutalorScientific().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAkar;
    private javax.swing.JButton buttonAkarx;
    private javax.swing.JButton buttonAngka0;
    private javax.swing.JButton buttonAngka1;
    private javax.swing.JButton buttonAngka2;
    private javax.swing.JButton buttonAngka3;
    private javax.swing.JButton buttonAngka4;
    private javax.swing.JButton buttonAngka5;
    private javax.swing.JButton buttonAngka6;
    private javax.swing.JButton buttonAngka7;
    private javax.swing.JButton buttonAngka8;
    private javax.swing.JButton buttonAngka9;
    private javax.swing.JButton buttonBS;
    private javax.swing.JButton buttonBagi;
    private javax.swing.JButton buttonCos;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonHasil;
    private javax.swing.JButton buttonKali;
    private javax.swing.JButton buttonKurang;
    private javax.swing.JButton buttonLog;
    private javax.swing.JButton buttonModulus;
    private javax.swing.JButton buttonPangkat;
    private javax.swing.JButton buttonPersen;
    private javax.swing.JButton buttonPhi;
    private javax.swing.JButton buttonSin;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton buttonTan;
    private javax.swing.JTextField display;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
